# Generated by Django 4.2.1 on 2023-05-18 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="课程名")),
                ("course_id", models.CharField(max_length=50, verbose_name="课程号")),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="姓名")),
                (
                    "teacher_id",
                    models.CharField(max_length=15, unique=True, verbose_name="工号"),
                ),
                ("age", models.IntegerField(verbose_name="年龄")),
                (
                    "sex",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女")], verbose_name="性别"
                    ),
                ),
                ("school", models.CharField(max_length=50, verbose_name="学院")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "教师",
                "verbose_name_plural": "教师",
                "ordering": ["teacher_id"],
                "permissions": [
                    ("can_view_student", "Can see available students"),
                    ("can_view_course", "Can see available courses"),
                    ("can_view_teacher", "Can see available teachers"),
                    ("can_view_score", "Can see available scores"),
                    ("can_view_course_time", "Can see available course time"),
                    ("can_change_score", "Can change scores"),
                    ("can_add_score", "Can add scores"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="姓名")),
                (
                    "student_id",
                    models.CharField(max_length=15, unique=True, verbose_name="学号"),
                ),
                (
                    "sex",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女")], verbose_name="性别"
                    ),
                ),
                ("age", models.IntegerField(verbose_name="年龄")),
                ("major", models.CharField(max_length=50, verbose_name="专业")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "学生",
                "verbose_name_plural": "学生",
                "ordering": ["student_id"],
                "permissions": [
                    ("can_view_student", "Can see available students"),
                    ("can_view_course", "Can see available courses"),
                    ("can_view_teacher", "Can see available teachers"),
                    ("can_view_score", "Can see available scores"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CourseTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekday", models.IntegerField(verbose_name="星期")),
                ("start", models.IntegerField(verbose_name="开始节")),
                ("end", models.IntegerField(verbose_name="结束节")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.course",
                        verbose_name="课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程时间",
                "verbose_name_plural": "课程时间",
            },
        ),
        migrations.CreateModel(
            name="CourseScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(verbose_name="成绩")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.student",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生成绩",
                "verbose_name_plural": "学生成绩",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="db.teacher",
                verbose_name="教师",
            ),
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(max_length=15, unique=True, verbose_name="工号"),
                ),
                ("name", models.CharField(max_length=32, verbose_name="姓名")),
                ("age", models.IntegerField(verbose_name="年龄")),
                (
                    "sex",
                    models.SmallIntegerField(
                        choices=[(1, "男"), (2, "女")], verbose_name="性别"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "教师",
                "verbose_name_plural": "教师",
                "ordering": ["employee_id"],
                "permissions": [
                    ("can_view_all", "Can view all"),
                    ("can_change_all", "Can change all"),
                    ("can_add_all", "Can add all"),
                    ("can_delete_all", "Can delete all"),
                ],
            },
        ),
    ]
